### ISSUE TITLE
Collision checking with custom .obj object

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Legacy#26] opened 2022-02-22 08:38 UTC
I have verified that placing a custom .obj object in the scene changes the sensory input point cloud information that the robot receives, but I'm wondering if I can see whether a given configuration of the robot collides with this object -- is this possible?

**Comment by tongzhoumu** [comment] 2022-02-23 03:56
Duplicate of https://github.com/haosulab/SAPIEN/issues/65

**Closed as completed by tongzhoumu** 2022-02-23 03:56 UTC
