### ISSUE TITLE
Input to Pretrained Models

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Legacy#15] opened 2021-11-03 05:16 UTC
Can the pretrained RL checkpoints be applied to RGB images from visualizer? Or does the input need to be RGBD, and if so, how do we obtain the depth information?

**Comment by tongzhoumu** [comment] 2021-11-03 09:31
Duplicate of https://github.com/haosulab/ManiSkill-Learn/issues/16

**Closed as completed by tongzhoumu** 2021-11-03 09:31 UTC
